### ISSUE TITLE
CLI: create runner API client

### ISSUE THREAD

**Issue by camerondurham** [camerondurham/runner#26]
This can be used to make request/response handling between client and server easier and allow us to document expected handling in our client types. With request/response handled in the client, the CLI logic can focus on reading files, forming requests and formatting response.

Some of this work is already done in CLI last issue, this will mainly be abstracting some logic into a client interface.

See TODOs in [cli/runner/client/client.go](https://github.com/camerondurham/runner/blob/main/cli/runner/client/client.go) and feel free to rename to make more sense in your use case.

Related page from Effective Go: https://go.dev/doc/effective_go#interfaces_and_types

**TODO**

- [ ] implement `NewClientFromConfig()` helper function
- [ ] refactor existing code into interface implementation struct for `Run()` and `Languages()` commands
- [ ] use new client in CLI to make requests
